name: stratagile_todo_test
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # State management
  flutter_hooks: ^0.21.2
  freezed_annotation: ^2.4.4
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  # local storage
  objectbox: ^4.1.0
  objectbox_flutter_libs: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator:
  build_runner: ^2.4.15
  custom_lint:
  riverpod_lint:
  objectbox_generator: any
  freezed: ^2.5.7

flutter:
  uses-material-design: true
